---
title: "Descriptive statistics & topic modeling"
output: html_document
date: "2023-10-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library("quanteda", quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
library("quanteda.textstats",quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
library("quanteda.dictionaries", quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
library("quanteda.textplots", quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
library("stm", quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
library("tidyverse", quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
library("lubridate")
#library("zoo", quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE)
#library(ggplot2)
#library(viridis)
```



# Topic Modelling

```{r}
combined <- read.csv('FINAL2.csv', stringsAsFactors = F)

# Reference: https://lubridate.tidyverse.org/
combined$date <- dmy(combined$date) 
combined$year <- year(combined$date)
combined$gender <- ifelse(combined$gender == 0, "Male", "Female")
combined$Art <- factor(combined$Art)
corpus_combined <- corpus(combined$Translated_Comments,
                       docvars = combined[,c("date", "year",
                                       "gender", "Art")])

# Tokenisation 
toks_com <- tokens(corpus_combined, remove_punct = TRUE, remove_symbols = TRUE, 
               remove_numbers = TRUE, remove_url = TRUE) %>%
        tokens_tolower() %>%
        tokens_remove(c('apnar', 'r', 'khub', 'apu', 'ei', 'e', 'a_href', 'ahm', 'na', 'ki', 'er', 'i', 'na', 's', 'href', 'amr', 'muza', 'xefer', 'm', 'a', 'deepanita', 'ai', 'm', 'chai', 'ridy', 'amr', 'bihu', 'ridi', 'farjana', 'danc', 'latif', 'curri', 've', 'hoy', 'ur', 'ar', 'pls', 'plz', 'onk', 'liza', 'bt', '#name', 'nusrat', 'umm', 'safa', 'manna', 'appl', 'valo','amar', 'onek' )) 
```

```{r}
# Document Feature Matrix
dfm_com <- dfm(toks_com) %>% 
       dfm_trim(min_termfreq = 2)
```

```{r}
?wordcloud
```

```{r}
write.csv(combined, "FINAL3.csv")
```



```{r}
# Converting the dfm object to stm object:
stm <- convert(dfm_com, to = "stm")
```

```{r}
k_search_output <- searchK(stm$documents, stm$vocab,
                           K = c(5,10,15,20,25), data = stm$meta,
                           verbose = FALSE, heldout.seed = 123)

k_search_output
```

```{r}
plot(k_search_output)
```

```{r}
#saving it as a RDS file
#saveRDS(k_search_output, "k_search_output.rds")
# Loading the saved k_search_output
#loaded_k_search_output <- readRDS("k_search_output.rds")

```


```{r}
#ntoken(corpus_combined) %>% sum()
#ntype(corpus_combined) %>% sum()
```



```{r}
set.seed(2)
stmodel <- stm(documents = stm$documents, 
                vocab = stm$vocab,
                K = 10, 
                prevalence =~ gender + s(year),
               #Hypothesis: We expect that gender has effect on discussion of certain topics.
               data = stm$meta, 
               verbose = FALSE)
```



```{r}
saveRDS(stmodel, file = "stm_youtube.rds")
```

```{r}
stmodel <- readRDS("stm_youtube.rds")
```

```{r}
toLDAvis(stmodel, docs = stm$documents)
```


```{r}
effect_estimates <- estimateEffect(1:10 ~ gender + s(year), stmodel, meta = stm$meta)
```

```{r}
summary(effect_estimates)
```




```{r}
labelTopics(stmodel, topics = 1, n = 10, frexweight = 0.5)
labelTopics(stmodel, topics = 2, n = 10, frexweight = 0.5)
labelTopics(stmodel, topics = 3, n = 10, frexweight = 0.5)
labelTopics(stmodel, topics = 4, n = 10, frexweight = 0.5)
labelTopics(stmodel, topics = 5, n = 10, frexweight = 0.5)
labelTopics(stmodel, topics = 6, n = 10, frexweight = 0.5)
labelTopics(stmodel, topics = 7, n = 10, frexweight = 0.5)
labelTopics(stmodel, topics = 8, n = 10, frexweight = 0.5)
labelTopics(stmodel, topics = 9, n = 10, frexweight = 0.5)
labelTopics(stmodel, topics = 10, n = 10, frexweight = 0.5)
```

Semantic Validation of the topics:


```{r}
cloud(stmodel, topic = 1, scale = c(3,.25)) # Culinary
cloud(stmodel, topic = 2, scale = c(3,.25)) # painting
cloud(stmodel, topic = 3, scale = c(3,.25)) # Emotive words
cloud(stmodel, topic = 4, scale = c(3,.25)) # Appreciating Women
cloud(stmodel, topic = 5, scale = c(3,.25)) # Music1
#cloud(stmodel, topic = 6, scale = c(5,.25)) 
cloud(stmodel, topic = 7, scale = c(3,.25)) # Dancing
#cloud(stmodel, topic = 8, scale = c(5,.25)) 
cloud(stmodel, topic = 9, scale = c(3,.25)) #Music 2
cloud(stmodel, topic = 10, scale = c(3,.25)) # Appreciating Appearance
```



Predictive validation of the topics:

```{r}
plot(effect_estimates, covariate = "gender", topics = c(1, 2, 3, 4, 5, 7, 9,10),
     model = stmodel, method = "difference",
     cov.value1 = "Male", cov.value2 = "Female",
     xlab = "More Female ... More Male", 
     main = "Female and Male",
     xlim = c(-.2, .2), labeltype = "custom", 
     custom.labels = c("Culinary","Painting","Emotive words","Appreciating Women","Music1","Dancing","Music 2","Appreciating Appearance"),
    ci.level=.99)
```

```{r}
table(combined$type_gender(combined$compound)) 
# "female singer", 1 
# "male singer", 2
# "female actor", 3, 
# "male actor", 4,
# "female dancer", 5,
# "male dancer", 6,
# "female painter", 7,
# "male painter", 8,
# "female chef", 9,
# "male chef", 10,
```



```{r}
effect <- estimateEffect(1:10 ~ gender, stmodel, meta = stm$meta)
```


```{r}
summary(effect)
```




